---
galaxy_info:
  author: Lenny Shirley
  description: Fetch all AAP Controller inventories (paginated). Sets controller_inventories. Requires controller_detect.
  license: MIT
  min_ansible_version: "2.15.0"
  galaxy_tags:
    - aap
    - controller
    - api
dependencies:
  - role: global_vars
...
