---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/ansible/molecule-podman:latest
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/usr/sbin/init"
    tmpfs:
      - /tmp
      - /run
    privileged: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        aap_url: "https://aap.example.com"
        aap_username: "admin"
        aap_password: "password"
        node_metrics_output_folder: "/tmp"
        node_metrics_output_formats:
          - markdown
verifier:
  name: ansible
