namespace: lennysh
name: aap_reports
version: 1.0.6-devel
readme: README.md
authors:
  - Lenny Shirley @lennysh
description: Ansible Collection for various custom Ansible Automation Platform Reports
license:
  - MIT-0
tags:
  - monitoring
  - aap
  - reports
  - automation
  - platform
  - ansible
  - metrics
  - subscription
dependencies: {}
repository: https://github.com/lennysh/lennysh.aap_reports
documentation: https://github.com/lennysh/lennysh.aap_reports/blob/devel/README.md
issues: https://github.com/lennysh/lennysh.aap_reports/issues
build_ignore:
  - __pycache__
  - .*
  - changelogs
  - collections
  - docs
  - ignore_other
  - playbooks
  - pyproject.toml
  - report_examples
  - roles/*/molecule
  - roles/*/tests
  - test-requirements.txt
  - test-workflow.txt
  - tests
  - tox-ansible.ini
  - vars.yml
...
