namespace: lennysh
name: aap_reports
version: 1.0.2-devel
readme: README.md
authors:
  - Lenny Shirley @lennysh
description: Ansible Collection for various custom Ansible Automation Platform Reports
license:
  - MIT-0
tags:
  - monitoring
  - aap
  - reports
  - automation
  - automationplatform
  - ansible
  - ansiblecollection
  - ansiblegalaxy
dependencies: {}
repository: https://github.com/lennysh/lennysh.aap_reports
documentation: https://github.com/lennysh/lennysh.aap_reports/blob/devel/README.md
issues: https://github.com/lennysh/lennysh.aap_reports/issues
build_ignore:
  - __pycache__/
  - ignore_other/
  - report_examples/
  - vars.yml
  - .github/
  - docs/
  - tests/
  - changelogs/
  - test-requirements.txt
  - tox-ansible.ini
  - test-workflow.txt
  - .ansible-lint
  - .ansible-lint-ignore
  - .yamllint.yml
  - .pre-commit-config.yaml
  - .prettierignore
  - pyproject.toml
  - collections/
  - playbooks/
  - roles/*/molecule/
  - roles/*/tests/
...
