---
galaxy_info:
  author: Lenny Shirley
  description: Obtain (login) and revoke (logout) AAP Controller OAuth2 tokens. Use in a block with always for cleanup.
  license: MIT
  min_ansible_version: "2.15.0"
  galaxy_tags:
    - aap
    - controller
    - token
dependencies: []
...
