---
- name: Generate AAP Node Metrics Reports
  hosts: localhost
  gather_facts: false
  vars:
    include_jobs_with_hosts: true
    output_folder: "{{ playbook_dir }}"
    output_filename: "aap_node_metrics_report"
    output_formats:
      - markdown
      - csv
      - html
      - json
      - yaml
      - xml
      - txt

  tasks:
    - name: Token Lifecycle Block
      block:
        - name: Login and get OAuth2 token
          ansible.builtin.include_role:
            name: lennysh.aap_reports.controller_token

        # - name: Display token info
        #   ansible.builtin.debug:
        #     msg:
        #       - "Token URL: {{ token_url }}"
        #       - "Token: {{ aap_token }}"

        - name: Get node metrics
          vars:
            report_node_metrics_output_folder: "{{ output_folder }}"
            report_node_metrics_output_filename: "{{ output_filename }}"
            report_node_metrics_output_formats: "{{ output_formats }}"
            report_node_metrics_include_jobs_with_hosts: "{{ include_jobs_with_hosts | default(false) | bool }}"
          ansible.builtin.include_role:
            name: lennysh.aap_reports.report_node_metrics

      always:
        - name: Logout (revoke token)
          ansible.builtin.include_role:
            name: lennysh.aap_reports.controller_token
          vars:
            controller_token_action: logout
...
