---
# Create controller hosts (all versions)
- name: Create controller hosts
  ansible.controller.host:
    name: "{{ item.name }}"
    inventory: "{{ (aap_dummy.inventories | selectattr('id', 'equalto', item.inventory_id) | list)[0].name }}"
    enabled: "{{ item.enabled }}"
    variables: "{{ item.variables | from_json }}"
    state: present
    controller_host: "{{ aap_hostname | default(omit) }}"
    controller_username: "{{ aap_username | default(omit) }}"
    controller_password: "{{ aap_password | default(omit) }}"
    controller_oauthtoken: "{{ aap_token | default(omit) }}"
    validate_certs: "{{ aap_validate_certs }}"
  loop: "{{ aap_dummy.hosts }}"
  loop_control:
    label: "{{ item.name }}"
...
