---
# Create controller inventories (all versions)
- name: Create controller inventories
  ansible.controller.inventory:
    name: "{{ item.name }}"
    organization: "{{ (aap_dummy.organizations | selectattr('id', 'equalto', item.organization_id) | list)[0].name }}"
    state: present
    controller_host: "{{ aap_url | default(omit) }}"
    controller_username: "{{ aap_username | default(omit) }}"
    controller_password: "{{ aap_password | default(omit) }}"
    controller_oauthtoken: "{{ aap_token | default(omit) }}"
    validate_certs: "{{ aap_validate_certs }}"
  loop: "{{ aap_dummy.inventories }}"
  loop_control:
    label: "{{ item.name }}"
  retries: "{{ aap_dummy_populate_retries }}"
  delay: "{{ aap_dummy_populate_retry_delay }}"
  register: inv_result
  until: inv_result is succeeded
...
